/*
 * This source file was generated by the Gradle 'init' task
 */
package planejadorfinanceiro.model;
import java.time.LocalDate;

public class Demonstracao {
    public static void main(String[] args) {
        // Criando um cliente
        Cliente cliente = new Cliente("joao", "joao@email.com", "123");

        // Criando o gerenciador
        GerenciadorFinanceiro gerenciador = new GerenciadorFinanceiro();
        gerenciador.setCliente(cliente);

        // Adicionando uma transação de entrada
        gerenciador.criarTransacaoEntrada("Salário", 3000.0, LocalDate.now());
        // Adicionando uma transação de saída
        gerenciador.criarTransacaoSaida("Aluguel", 1200.0, LocalDate.now());

        // Adicionando uma meta financeira
        gerenciador.criarMeta("Viagem", 5000.0, LocalDate.of(2024, 12, 31));

        // Exibindo informações do cliente
        System.out.println("Cliente: " + cliente.getNome());
        System.out.println("Email: " + cliente.getEmail());
        System.out.println("Saldo: R$ " + cliente.getSaldo());
        System.out.println("\nTransações:");
        for (Transacao t : cliente.getTransacoes()) {
            System.out.println("- " + t.getNome() + ": R$ " + t.getValor() + " (" + t.getTipo() + ")");
        }
        System.out.println("\nMetas:");
        for (Meta m : cliente.getMetas()) {
            System.out.println("- " + m.getNome() + ": R$ " + m.getValorAlvo() + " até " + m.getPrazoFinal());
        }
    }
}
